# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# environment variables
env:
  JENKINS_HOST: https://jenkins.example.com/ ## jenkins base url
  JENKINS_JOB: testJobs/HelloWorld ## builds the HelloWorld job inside testJobs
  JENKINS_PARAMS: environment=dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      -
        name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_HOST: ${{ env.JENKINS_HOST }}
          JENKINS_JOB: ${{ env.JENKINS_JOB }}
          JENKINS_PARAMS: ${{ env.JENKINS_PARAMS }}
          
  
          




